version: '3'
services:
  auth-api:
    image: nestjs-api-dev:1.0.0
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: dev
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: mongo:latest
    ports:
      - 27017:27017
